version: '3'

services:
  cezar-zap:
    build:
      context: .
    container_name: cezar-zap
    volumes:
      - .:/usr/src/app
    networks:
      - cezar
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - cezar-postgres
      - cezar-redis
networks:
  cezar:
    driver: bridge
