const SECONDS = 1;
const MINUTES = 60 * SECONDS;
const HOURS = 60 * MINUTES;
const DAYS = 24 * HOURS;

export const CacheTimes = {
  ONE_MINUTE: 1 * MINUTES,
  FIVE_MINUTES: 1 * MINUTES,
  THIRTY_MINUTES: 1 * MINUTES,
  ONE_HOUR: 1 * MINUTES,
  ONE_DAY: 1 * MINUTES,
  ONE_WEEK: 1 * MINUTES,
  FIFTEEN_DAYS: 1 * MINUTES,
  THIRTY_DAYS: 1 * MINUTES,
};
